# .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on: 
  push:
    branches:
      - main  # Executa a ação em qualquer push na branch 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step para configurar o GitHub Pages para usar a branch main e o caminho root
      - name: Configure GitHub Pages to use branch 'main' and path 'root'
        env:
          GITHUB_TOKEN: ${{'${{'}} secrets.PERSONAL_GITHUB_TOKEN${{'}}'}}
          REPO_OWNER: ${{'${{'}} github.repository_owner${{'}}'}} 
          REPO_NAME: ${{'${{'}} github.event.repository.name${{'}}'}}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/pages \
            -d '{"source":{"branch":"main","path":"/"}}'